version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
  disable:
    - errcheck
    - depguard # sometimes too restrictive for small projects

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
